/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

 
repositories {
    mavenCentral()                                                  
}

dependencies {
  implementation 'com.quickbirdstudios:opencv:3.4.1'
}